### ISSUE TITLE
Quicksort [Java]

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#145]
There seems to be some issue in java implementation of Quick Sort on this repo [here](https://github.com/iiitv/algos/blob/master/quicksort/QuickSort.java) ,if we take repeated inputs then it goes into infinite loop.

**Comment by Prakash2403** [comment]
I guess there must be equality on either of inner while loop in first function.

**Comment by Monal5031** [comment]
I tried giving equality to both loops but I got `java.lang.StackOverflowError` 😕

**Comment by Prakash2403** [comment]
Don't give equality on both loops, try on either one of them but not both.
My laptop is broken that's why I can't test it right now. So, I am not sure
about the result.

On 18-Apr-2017 1:33 AM, "Monal Shadi" <notifications@github.com> wrote:

I tried giving equality to both loops but I got java.lang.StackOverflowError
😕

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iiitv/algos/issues/145#issuecomment-294575075>, or mute
the thread

**Comment by Prakash2403** [comment]
This algorithm will fail for repeated elements, because assume if A[L], pivot and A[R] become equal, then neither L nor R will be increased or decreased, and swapping will give no change because A[L] and A[R] is equal. Condition for outer while loop will never fail, hence infinite loop will run.

**Comment by Monal5031** [comment]
@Prakash2403 Should we move with the other method of quicksort wherein we actually shift the elements to left of pivot.

**Comment by Prakash2403** [comment]
Yes
