### ISSUE TITLE
GitMate breaks down

### ISSUE THREAD

**Issue by sils** [iiitv/algos#500]
Hi,

I'm one of the GitMate maintainers and I saw in our logs that you're using it because we got an error there.

Apparently coala times out, seems to be taking longer than 10 minutes - does it take that long locally?

CC @nkprince007 @fneu from GitMate as well, hope we can fix it

**Comment by singhpratyush** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by singhpratyush** [comment]
The contributors most likely able to help are:

@singhpratyush

**Comment by sils** [comment]
ok this is an issue on our side, we think we've found it and deploying a fix within the next minutes

**Comment by sils** [comment]
We've released our hotfix, sorry for the disturbance; do let us know if we can do anything else to make GitMate better for you!
