### ISSUE TITLE
Queue [Java]

### ISSUE THREAD

**Issue by sebasrp** [iiitv/algos#509]
#### This issue is about [Queue](http://www.cdn.geeksforgeeks.org/stack-data-structure-introduction-program/).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by singhpratyush** [comment]
The contributors most likely able to help are:

@manish1997

Possible duplicate or related issues are:

- #345: Gradient Descent [Python]
- #478: Algo/largest_sum_contiguous_subarray [C++]
- #391: Shell Sort [Java]
- #428: Add badges to README.md
- #427: Sleep Sort [Golang]

**Comment by singhpratyush** [comment]
@sebasrp: Please put a proper link in the description. Use the space provided.

@mohitkyadav: Gitmate is strangely marking all issues as `Algorithm`, sorry about that. Will try to resolve it.

**Comment by jasm123** [comment]
This issue is about [Queue](http://www.geeksforgeeks.org/queue-set-1introduction-and-array-implementation/).

- [ ]  Issue Title is in form Algo/DS Name [Language].
- [ ]  I searched or browsed the repo’s other issues to ensure this is not a 
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

PR hasn't been made since a week, and I would like to work on this.
