### ISSUE TITLE
Add me to repo

### ISSUE THREAD

**Issue by yashLadha** [iiitv/algos#71]
It would be good if one raises an issue for adding as contrib rather than commenting in an ongoing PR, because it is not referenced to the PR.

**Comment by aviaryan** [comment]
Agreed. Probably "add me to team" things should go in `iiitv/getmein` or some another repo, not this.
But this problem is not that big. There are only a few members which are a part of IIITV org but not of Members team. And if someone is not a part of IIITV org, he should not work on this repo in the first place. 
So maybe we can add a section in Contributing guidelines with something like "check if you are a member of iiitv org and part of Members team, if not open an issue at getmein" . 

@yashLadha What do you think? If you agree, please send a PR.

**Comment by yashLadha** [comment]
Indeed,
I will send the PR. @aviaryan

**Comment by yashLadha** [comment]
I should add this check in PULL_REQUEST_TEMPLATE
